env:
  global:
    - secure: "OR4E8SSRrZXC85sx6lWAKbLA2A1CjGzLtcf8QpojhOvg+YV2ikvNyfEMdiOljuYelE5syvlC2q890F45pkihzCNJhT7Ef2ionJwBLCAtEDCM8acOUeTIa15W5qcLcoAy9Isbky49D6eHyXlpWhvrR2TUVtcEy+k89ppawiGGIbQibAiI1ld/Mv4GmlQ7qWq9GIyIGVqYQbatib8ej8J8qDlvr0l6WPwJ2xrtNtCzHr9YxP/uuc5VsFrr509spWxj/Ai/uf+gim5fLcMtx0MTDySHfjhTfdt+N7RVeTYndszeI3TpvfF0DuGTq/DoLepgo0OsmSbSsTHxuvrYNZRhA4/9AFK7rMzPwYDorg+uk7d2XwVsNU3pAIN/up1+Km84iwYUXrhk1kKHhmIxaNO9+p3qpZNMzAFiLVYIZJBo3OCWPMAy6b0+dZlUigyUFSwGg0EGuFgrWaXJyx7NYb6NBmefeCquH9f0Cua0SjawbWVzLsfXZJ+WdAgdex8hpRfCGeikcgjy8TfhNtIOyXPwe4tTr/l3LlysIBUdAwhClpCcsA3CL9xaY/eqFDbbISnk8QhRAJWd8zSvqTWOohOIFd1DZ3tb04PFONbhPN8JOc0wJIf4Sv9AIyv3GU4JcDR6SWu66sd4o62KUD0jaMHF2hXC1njNlWPCQ2lW8VIFNPc="
    - secure: "JOdbhDz1q/2tmyaFMwaEbqGTJ9gChsCwvzNrpVlWedf3J0j9q2KpfDHznBVQRjXhILNKCGIwrEVCqjeyxwZXh5h4KmsronTJLWOQr1v7dmLEATftaRHEhwsG6T1lVJAYLEa6vIZ/D8w2fehqhgE1kcgKiejq78EKomRPbU/kWPGs/QAnbTh3JoWnepTU+Pma+qqwFqujghM1QhySoTjHY/s/vatIUEzZS8BOluL9O4Bd6rMzPJaOt2YpXXXiZV7lBFRnW2KNw0gkHRC4Yf0VRNzBXBM7XkTVx1Qg+RpqTGPnXASrxwbWMbAhj/EkF4mvWcrwJsICCmJ4fpOMvvzq9NxAvmcLkBY7Fzd9zcf5Xqn0oEJIbFuWXjtaIU/9K1sNzam6YuELuxUG1qy0afqoAKRzMB97vxCtiKU9gQbFMs2JEOmCTO+DQ6udXH+KjTbkxFalVDSZFo0Nmbj0H6pY4r7ml7FUE4w8tDJib1wNWL5VCdQ4z/Wf48YDKtof/iqvsNFapQ73R9klltXOhMf0s012/iJRGS0RnzmEtrUC7Vp9OUaMrxLk8vVBLIS/AEZ+vsMGYIdWY7p+froR1PeFc9FPigX/YZrcoL11xtNa+J4mQrk+xhRSfzUeA2M3XtvQ7HoiAx6znVciHZisfax/tpr7Mngxbr708fjzT85DwuU="
    - secure: "eYqgOulhgC51h8qEXNV76xBecYAeWS7Ad/OwywB20JHzdXbz84HdSTdlhYZdsS3O+6jhZsRe8Qi5EFhfEPesuTviQ7ZBAovGnWfL+llTsWxp29fE1dMLJVGIcMYXDwOnLEQMT7j3a7pzdzoJr2TNqu8o4wkNQ0zJM1I0S0bqMGNxs7/fewDtpmFpQ1TxjBHuzvd2wA+yLF9MGRW+KudLJuwihad1bLqyi/2W8UmmgSgENUSf9h1bxeUB94T+2mKmJFANkaBwuskYM57kvmhFzMFXtPel6n4gcbdOrojmdCjgol4U9wpOE5xeZCarEZYposLqRxNDt7WyLx4wLR4kM5jBUlCA++vN4cXaTg5QxKP73tpILlFUgVQlW/P5t0UwVwVfwQMOwFiMsOkfukkV6Jna+ls6QK3cFlAAnwC8ATdTUmKdBnf5u04IFBGgqNVqG+jmLba5e9HsvAFUKMRO3f/7Mnr+4eZ2Bbi25ez9DdwVhQYQ4iFcRhuQ6Uxn1z3w0QpKIyyoCkP95uuhRNxSHwyk/F4JQQ4KNKphcuzAeU4+oU/NEQFJL+VsSimWFltu488ZhXtLcoQb3520O3EtVehpEWtRzN3vdaNuMLIzgKzPUTLG3VhmQihCdA25uc5a/xBdenJEwVX6M2N+e6FoYOkQ/Foe4A/yEXlGjZYloU4="
    - secure: "QNHzdHYVuRCGKcpZqadOUSCn4P0ZEP3OJE2NA1iu5eS1IyoGzO5Ho/3oVP8nVsrtoVxDjwlEAZhpABmk6zkHQBDlxJuE5cNEftcv3Kz0mj3uLP3twslpmzjYlOBjyJfbRjydbchBV6vbQFXFeb1XW+7Lq1rzK6xrONaoPfjUC6KoaOksjjNwIf0k7f6gIqVdtvzeVsVW90TLGamniQsfjoXWzc36VhuirrTg8ZpMPxcyl1rsfOu6aA93JlM7E1Ao9NncMGWbXfoBJ5knM0fPdLoEjcYbPy05U23OpVAMbg7KGIXSdtkF3YaepKIWk4Pq6nrjBObYZ6TUInE6XfLVxr0XZ0Sea4gHvD5QplJ47BaBSlDxO0ok6C1yFuKBRRrnypIWRoEtuFXIMNvwERwudWja3EToDCqhJGUsQWR0l2tVXXdDCxoZcNl/AuPxkzQpwg2hixdAcbGqykda3DL6WUgeYAKj5VVGLOl2xtyqiMyiNdu3rEwEdrdtjbkAtIddwx6siZAgjQisxipfleNsnTLafFGhx4gGM27CX8eUVS32PsLwA0RsEDGdbb+klBo6yIuWo/Zz6sOBK6udPTV5XeMRSq5+sOMSJ1Grgq1WywPRzguqLu914sCdXSL36bZ4IF19s/GVQuWhOJlrJ7Ctdlq7xznpbpi5qAGubA1R+ik="
after_success: |
  semantic-release \
    --prepare @conveyal/maven-semantic-release \
    --publish @semantic-release/github,@conveyal/maven-semantic-release \
    --verify-conditions @semantic-release/github,@conveyal/maven-semantic-release \
    --verify-release @conveyal/maven-semantic-release \
    --use-conveyal-workflow \
    --dev-branch=develop
before_install: |
  if [[ "$TRAVIS_PULL_REQUEST" = false ]] && [[ "$TRAVIS_BRANCH" = main ]]; then
    openssl aes-256-cbc -K $encrypted_d81b39e7ac43_key -iv $encrypted_d81b39e7ac43_iv -in maven-artifact-signing-key.asc.enc -out maven-artifact-signing-key.asc -d
    gpg --import --batch maven-artifact-signing-key.asc
  fi
before_script:
  - nvm install '12'
  - yarn global add https://github.com/conveyal/maven-semantic-release.git#8eb976c8ec57b2fd1cee86f119f80ab1f8a38948 semantic-release
cache:
  directories:
    - $HOME/.m2
    - $HOME/.cache/yarn
install: true
jdk:
  - openjdk8
language: java
notifications:
  email: false
script:
  - mvn package
sudo: false