name: Build and Test

on:
  push:
    branches:
      - develop
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build_and_test:
    name: Build and Test with JDK ${{ matrix.java }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [8, 11]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          cache: 'maven'
          distribution: 'adopt'

      - name: Build and analyse
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: mvn -B package -DskipTests -Dgpg.skip -Pdependency-check

      - name: Test core
        run: mvn -B -Dgpg.skip test --file core/pom.xml
