name: CI

on:
  push:
    branches-ignore:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  legacy_build_and_test:
    name: Legacy CI with JDK ${{ matrix.java.version }}
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      matrix:
        java:
          - { version: 8 }
          - { version: 11 }

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up JDK
        uses: actions/setup-java@v4.7.1
        with:
          java-version: ${{ matrix.java.version }}
          cache: 'maven'
          distribution: 'adopt'

      - name: Build and analyse
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: mvn -B -Plegacy -pl core,ui.apps,ui.apps.structure,ui.config,all -am package -DskipTests -Dgpg.skip

      - name: Test core
        run: mvn -B -Plegacy -Dgpg.skip test --file core/pom.xml

  cloud_build_and_test:
    name: Cloud CI with JDK ${{ matrix.java.version }}
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      matrix:
        java:
          - { version: 17 }
          - { version: 21 }

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up JDK
        uses: actions/setup-java@v4.7.1
        with:
          java-version: ${{ matrix.java.version }}
          cache: 'maven'
          distribution: 'adopt'

      - name: Build and analyse
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: mvn -B -Pcloud -pl core,ui.apps,ui.apps.structure,ui.config.cloud,all.cloud -am package -DskipTests -Dgpg.skip

      - name: Test core
        run: mvn -B -Pcloud -Dgpg.skip test --file core/pom.xml
