name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    name: ${{ matrix.profile }} CI with JDK ${{ matrix.java-version }}
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - profile: legacy
            java-version: '8'
            run-sonar: false
          - profile: legacy
            java-version: '11'
            run-sonar: false
          - profile: cloud
            java-version: '17'
            run-sonar: false
          - profile: cloud
            java-version: '21'
            run-sonar: true

    uses: ./.github/workflows/reusable-ci-maven.yml
    with:
      profile: ${{ matrix.profile }}
      java-version: ${{ matrix.java-version }}
      run-sonar: ${{ matrix.run-sonar }}
    secrets:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
