name: Release to Maven Central

on:
  push:
    branches:
      - main
      - prerelease

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: "adopt"
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}

      - name: Cache Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and analyse
        run: mvn -B package -DskipTests -Dgpg.skip -Pdependency-check

      - name: Test core
        run: mvn -B -Dgpg.skip test --file core/pom.xml

      - name: Publish to Maven Central
        id: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
        run: yarn semantic-release --use-conveyal-workflow --dev-branch=prerelease
