name: Release to Maven Central

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      packages: write

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: pnpm/action-setup@v4.1.0
        name: Install pnpm

      - name: Install Node.js
        uses: actions/setup-node@v4.4.0
        with:
          cache: 'pnpm'
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup JDK
        uses: actions/setup-java@v4.7.1
        with:
          java-version: 8
          cache: 'maven'
          distribution: 'adopt'

      - name: Publish to Maven Central
        id: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_OPTS: '-Pcentral-publish'
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          JRELEASER_GPG_KEYNAME: ${{ secrets.OSSRH_GPG_KEY_NAME }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.OSSRH_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        run: pnpm semantic-release
