name: Release Dry Run

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

concurrency:
  group: release-dry-run-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dry_run:
    permissions:
      contents: write
      issues: write
      packages: write
    uses: ./.github/workflows/reusable-release.yml
    with:
      dry-run: true
      java-version: '21'
      gpg-public-key: ${{ vars.OSSRH_GPG_PUBLIC_KEY }}
    secrets:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      OSSRH_GPG_KEY_NAME: ${{ secrets.OSSRH_GPG_KEY_NAME }}
      OSSRH_GPG_SECRET_KEY_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
      OSSRH_GPG_SECRET_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
