name: Release Dry Run

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

concurrency:
  group: release-dry-run-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dry_run:
    permissions:
      contents: read
    uses: ./.github/workflows/reusable-release.yml
    with:
      dry-run: true
      java-version: '17'
      gpg-public-key: ${{ vars.OSSRH_GPG_PUBLIC_KEY }}
    secrets: inherit
