name: Sonarcloud

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4.7.1
        with:
          cache: 'maven'
          distribution: 'adopt'
          java-version: 21

      - name: Cache SonarCloud packages
        uses: actions/cache@v4.2.3
        with:
          key: ${{ runner.os }}-sonar
          path: ~/.sonar/cache
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4.2.3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyse
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B -Dgpg.skip verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Pcoverage-report -Dsonar.projectKey=aem-vite_aem-vite
